In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('Ecommerce Customers.csv')

In [6]:
df

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,mstephenson@fernandez.com,"835 Frank Tunnel\nWrightmouth, MI 82180-9605",Violet,34.497268,12.655651,39.577668,4.082621,587.951054
1,hduke@hotmail.com,"4547 Archer Common\nDiazchester, CA 06566-8576",DarkGreen,31.926272,11.109461,37.268959,2.664034,392.204933
2,pallen@yahoo.com,"24645 Valerie Unions Suite 582\nCobbborough, D...",Bisque,33.000915,11.330278,37.110597,4.104543,487.547505
3,riverarebecca@gmail.com,"1414 David Throughway\nPort Jason, OH 22070-1220",SaddleBrown,34.305557,13.717514,36.721283,3.120179,581.852344
4,mstephens@davidson-herman.com,"14023 Rodriguez Passage\nPort Jacobville, PR 3...",MediumAquaMarine,33.330673,12.795189,37.536653,4.446308,599.406092
5,alvareznancy@lucas.biz,"645 Martha Park Apt. 611\nJeffreychester, MN 6...",FloralWhite,33.871038,12.026925,34.476878,5.493507,637.102448
6,katherine20@yahoo.com,"68388 Reyes Lights Suite 692\nJosephbury, WV 9...",DarkSlateBlue,32.021596,11.366348,36.683776,4.685017,521.572175
7,awatkins@yahoo.com,Unit 6538 Box 8980\nDPO AP 09026-4941,Aqua,32.739143,12.351959,37.373359,4.434273,549.904146
8,vchurch@walter-martinez.com,"860 Lee Key\nWest Debra, SD 97450-0495",Salmon,33.987773,13.386235,37.534497,3.273434,570.200409
9,bonnie69@lin.biz,"PSC 2734, Box 5255\nAPO AA 98456-7482",Brown,31.936549,11.814128,37.145168,3.202806,427.199385
10,andrew06@peterson.com,"26104 Alexander Groves\nAlexandriaport, WY 282...",Tomato,33.992573,13.338975,37.225806,2.482608,492.606013
11,ryanwerner@freeman.biz,Unit 2413 Box 0347\nDPO AA 07580-2652,Tomato,33.879361,11.584783,37.087926,3.713209,522.337405
12,knelson@gmail.com,"6705 Miller Orchard Suite 186\nLake Shanestad,...",RoyalBlue,29.532429,10.961298,37.420216,4.046423,408.640351
13,wrightpeter@yahoo.com,"05302 Dunlap Ferry\nNew Stephaniehaven, MP 42268",Bisque,33.190334,12.959226,36.144667,3.918542,573.415867
14,taylormason@gmail.com,"7773 Powell Springs Suite 190\nSamanthaland, N...",DarkBlue,32.387976,13.148726,36.619957,2.494544,470.452733
15,jstark@anderson.com,"49558 Ramirez Road Suite 399\nPhillipstad, OH ...",Peru,30.737720,12.636606,36.213763,3.357847,461.780742
16,wjennings@gmail.com,"6362 Wilson Mountain\nJohnsonfurt, GA 15169",PowderBlue,32.125387,11.733862,34.894093,3.136133,457.847696
17,rebecca45@hale-bauer.biz,"8982 Burton Row\nWilsonton, PW 88606",OliveDrab,32.338899,12.013195,38.385137,2.420806,407.704548
18,alejandro75@hotmail.com,"64475 Andre Club Apt. 795\nPort Dannytown, PW ...",Cyan,32.187812,14.715388,38.244115,1.516576,452.315675
19,samuel46@love-west.net,544 Alexander Heights Suite 768\nNorth Johnvie...,LightSeaGreen,32.617856,13.989593,37.190504,4.064549,605.061039
20,megan33@gmail.com,"84426 Julia Vista\nNorth Teresa, KY 50756",PeachPuff,32.912785,11.365492,37.607793,4.599937,534.705744
21,agolden@yahoo.com,"PSC 2490, Box 2120\nAPO AE 15445-2876",Black,33.503087,12.877984,37.441021,1.559152,419.938775
22,vstafford@hotmail.com,"PSC 5723, Box 8159\nAPO AA 74738",Olive,31.531604,13.378563,38.734006,2.245148,436.515606
23,denise22@hernandez-townsend.com,USNS Cardenas\nFPO AA 85439-9449,Silver,32.903251,11.657576,36.772604,3.919302,519.340989
24,youngbarbara@yahoo.com,"019 Elliott Tunnel Suite 190\nNicholsbury, WV ...",Wheat,34.507551,12.893670,37.635756,5.705154,700.917092
25,william25@mcconnell.com,"9495 Mary Fall Apt. 777\nGlassport, ND 17957-5596",Teal,33.029332,11.765813,37.738525,2.721736,423.179992
26,ijones@schaefer-carr.net,"657 Judith Crossroad\nHancockchester, VI 75658...",Linen,33.541231,12.783892,36.430650,4.648199,619.895640
27,heatherhall@yahoo.com,"8522 Regina Port Suite 782\nPort Kaitlin, TX 5...",MediumSlateBlue,32.335990,13.007819,37.851779,2.996365,486.838935
28,tinasmith@martinez.info,"40000 Ann Port Suite 474\nYoungberg, MS 03651",LemonChiffon,33.110205,11.982045,35.293088,3.923489,529.537665
29,chasejennifer@hotmail.com,9507 Robert Prairie Apt. 601\nEast Crystalview...,DarkOrchid,33.105438,11.965020,37.277812,4.742578,554.722084
...,...,...,...,...,...,...,...,...
470,kennethperry@bowen.org,"272 Frederick Lodge\nEast Andrew, FL 07414",SlateGray,32.518197,11.509253,36.599289,3.022676,424.728774
471,prussell@lopez.com,"9985 Wolf Pass\nBrandimouth, CA 63346",Bisque,34.523020,11.405770,36.378271,4.041245,541.049831
472,mosleyjacob@yahoo.com,"PSC 1790, Box 8872\nAPO AE 01821-4769",Orange,33.665990,12.263718,38.860234,3.139527,469.383146
473,rhaas@yahoo.com,"4502 Jennifer Prairie Suite 029\nLake Jesse, L...",DimGray,31.609840,12.710701,36.166463,2.562819,444.545550
474,antonioharris@hotmail.com,"4307 Nicholas Drive Apt. 259\nRamirezberg, AS ...",MediumBlue,33.700886,13.471578,37.071643,2.379076,492.556834
475,austinthomas@gmail.com,"5855 Gross Burgs Suite 169\nBallland, AS 98525",AntiqueWhite,33.811733,11.186809,36.298893,4.301996,535.321610
476,bethsullivan@reed.net,"80500 Mary Corners Apt. 225\nWallsville, ME 80526",Beige,34.336677,11.246813,38.682584,2.094762,408.958336
477,ncummings@yahoo.com,"344 Jessica Stravenue\nNew Brian, MA 04730-6761",Beige,31.061325,12.357638,36.166042,4.089331,487.555458
478,hking@hotmail.com,"85181 Christian Courts Suite 758\nLarryfurt, M...",PeachPuff,33.069768,11.764326,36.875026,3.516051,487.646232
479,annstone@hotmail.com,"543 Reynolds Burg\nMelindaberg, KY 46631",LightPink,34.606242,11.761884,38.126520,1.820811,402.167122
480,christopher44@hotmail.com,"549 Anna Avenue\nPort Laura, CA 76209-9339",WhiteSmoke,34.238242,11.550300,35.769330,4.183144,551.023002
481,autumn88@mendoza-mills.com,"214 Obrien Lakes Suite 572\nSouth Jeremy, KS 5...",MediumOrchid,32.047815,12.482670,35.536025,3.393903,497.389558
482,dhudson@ramos.net,"5661 Grant Centers\nStevensfurt, CT 53959",Olive,30.971676,11.731364,36.074551,4.426364,494.638610
483,egomez@hotmail.com,"768 Riley Pine Apt. 624\nKellymouth, OK 98992-...",MistyRose,33.606851,12.214074,37.198428,2.905238,479.247417
484,kimberlyruiz@smith-gordon.com,"503 Adams Pines Apt. 638\nNorth Ashleyside, AZ...",DarkRed,33.448125,11.903757,36.874544,2.782758,462.656519
485,mooremichelle@logan.com,"07813 Randy Point\nLake Thomasberg, MO 06013-9920",Pink,33.369381,12.222484,36.355235,3.447018,515.502480
486,aaron22@gmail.com,"38678 Sean Drive Suite 293\nKarentown, IA 7830...",DarkGray,33.452295,12.005916,36.534096,4.712234,576.477607
487,michelleshepherd@price.com,"6820 Erica Vista Apt. 418\nBrightside, IA 50639",Orchid,32.904692,11.913745,36.058648,1.228112,357.857984
488,zscott@wright.com,"9909 Hoffman Ranch Suite 195\nScotthaven, SC 5...",PeachPuff,35.630854,12.125402,38.187764,4.019051,597.739879
489,tracy79@wheeler.net,"513 Moore Crescent Apt. 416\nAmandaberg, GU 03...",Magenta,32.246350,11.305551,37.133127,1.707390,327.377953
490,brian28@sanchez.org,"7446 Mary Ferry\nLake Sherryfurt, GA 49066-0207",GhostWhite,34.695591,11.608997,37.684877,3.163092,510.401388
491,leonardhancock@hotmail.com,64147 Alexander Station Apt. 474\nEast Jasonvi...,SeaShell,34.343922,11.693058,36.812934,3.447093,510.501478
492,davidsonkathleen@gmail.com,"70128 Zimmerman Overpass\nRobertsshire, VA 59860",DarkBlue,33.680937,11.201570,37.835448,2.208814,403.819520
493,nathan84@lowery.net,"01242 Stephanie Ways Suite 003\nChurchville, M...",MediumSeaGreen,32.060914,12.625433,35.539142,5.412358,627.603319
494,kellydeborah@chan.biz,"354 Sanchez Wall Suite 884\nJuliabury, VI 39735",DarkTurquoise,33.431097,13.350632,37.965972,2.768852,510.661792
495,lewisjessica@craig-evans.com,"4483 Jones Motorway Suite 872\nLake Jamiefurt,...",Tan,33.237660,13.566160,36.417985,3.746573,573.847438
496,katrina56@gmail.com,"172 Owen Divide Suite 497\nWest Richard, CA 19320",PaleVioletRed,34.702529,11.695736,37.190268,3.576526,529.049004
497,dale88@hotmail.com,"0787 Andrews Ranch Apt. 633\nSouth Chadburgh, ...",Cornsilk,32.646777,11.499409,38.332576,4.958264,551.620145
498,cwilson@hotmail.com,"680 Jennifer Lodge Apt. 808\nBrendachester, TX...",Teal,33.322501,12.391423,36.840086,2.336485,456.469510
499,hannahwilson@davidson.com,49791 Rachel Heights Apt. 898\nEast Drewboroug...,DarkMagenta,33.715981,12.418808,35.771016,2.735160,497.778642

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
Email                   500 non-null object
Address                 500 non-null object
Avatar                  500 non-null object
Avg. Session Length     500 non-null float64
Time on App             500 non-null float64
Time on Website         500 non-null float64
Length of Membership    500 non-null float64
Yearly Amount Spent     500 non-null float64
dtypes: float64(5), object(3)
memory usage: 31.3+ KB

In [8]:
df.drop(['Email','Address','Avatar'],axis=1,inplace=True)

In [9]:
df.head()

,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,34.497268,12.655651,39.577668,4.082621,587.951054
1,31.926272,11.109461,37.268959,2.664034,392.204933
2,33.000915,11.330278,37.110597,4.104543,487.547505
3,34.305557,13.717514,36.721283,3.120179,581.852344
4,33.330673,12.795189,37.536653,4.446308,599.406092

In [10]:
df.corr()

,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
Avg. Session Length,1.000000,-0.027826,-0.034987,0.060247,0.355088
Time on App,-0.027826,1.000000,0.082388,0.029143,0.499328
Time on Website,-0.034987,0.082388,1.000000,-0.047582,-0.002641
Length of Membership,0.060247,0.029143,-0.047582,1.000000,0.809084
Yearly Amount Spent,0.355088,0.499328,-0.002641,0.809084,1.000000

In [11]:
y=(df['Yearly Amount Spent'])

In [12]:
y.head()

0    587.951054
1    392.204933
2    487.547505
3    581.852344
4    599.406092
Name: Yearly Amount Spent, dtype: float64

In [13]:
df.drop('Yearly Amount Spent',axis=1,inplace=True)

In [14]:
df.head()

   Avg. Session Length  Time on App  Time on Website  Length of Membership
0            34.497268    12.655651        39.577668              4.082621
1            31.926272    11.109461        37.268959              2.664034
2            33.000915    11.330278        37.110597              4.104543
3            34.305557    13.717514        36.721283              3.120179
4            33.330673    12.795189        37.536653              4.446308

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,Y_train,Y_test=train_test_split(df,y,test_size=0.2)

In [17]:
l_reg=LinearRegression()

In [18]:
l_reg.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [19]:
print(l_reg.coef_)
print(l_reg.intercept_)

[26.06755562 38.82037442  0.15167969 61.67105594]
-1053.7703380373312

In [20]:
y_pred=l_reg.predict(X_train)

In [21]:
l_reg.score(X_train,Y_train)

0.9826519595384228

In [23]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=l_reg, X=X_train, y=Y_train, cv=10)
model_accuracy = accuracies.mean()
model_standard_deviation = accuracies.std()

In [24]:
accuracies

array([0.97977005, 0.97863275, 0.98503935, 0.98422501, 0.98977042,
       0.97843172, 0.97521277, 0.97946991, 0.98391294, 0.97302704])

In [25]:
model_accuracy

0.9807491960193524

In [26]:
model_standard_deviation

0.004739277852774333

In [27]:
y_pred

array([590.63579745, 518.67381557, 525.73917796, 534.30800372,
       548.82723984, 537.62796765, 512.51897083, 657.69028508,
       473.37146882, 458.02655498, 493.12490393, 383.58168514,
       652.25232554, 432.18376383, 716.33485711, 573.24681227,
       541.01824805, 510.03492585, 562.75331046, 460.60086809,
       588.50997322, 725.44031033, 450.61952855, 526.77344468,
       440.52090324, 590.36644744, 558.28493884, 548.17113301,
       694.14348695, 463.10180361, 611.27974285, 456.27152416,
       484.8104455 , 284.22567776, 476.49771363, 539.76148897,
       519.20551592, 379.68970404, 467.57564962, 486.38396243,
       552.68258891, 512.60567143, 474.68260205, 523.46895272,
       455.10006659, 648.98886039, 520.51736776, 476.98985701,
       569.55377846, 524.40889273, 461.22222086, 568.23813182,
       447.19310425, 569.2363286 , 589.03762403, 556.87652449,
       418.81638642, 501.5915688 , 379.87722092, 555.14025321,
       551.79204802, 523.26538284, 411.55413366, 493.32962643,
       495.47213999, 491.85300007, 472.00760624, 376.19149332,
       482.43789129, 402.49786048, 584.53985535, 432.18258551,
       471.37193753, 563.93979476, 416.72643009, 577.78252698,
       490.37297466, 482.34719098, 570.97198749, 481.43145667,
       503.57990005, 397.96991176, 437.87421732, 558.00216202,
       529.96475006, 573.44384121, 456.12194449, 435.27961887,
       456.06061035, 376.58490328, 516.6944254 , 643.56378132,
       467.99399591, 483.79018287, 499.94820082, 535.47195889,
       548.09284985, 419.63785346, 534.51985383, 466.23565523,
       513.17806217, 478.41541251, 601.92873527, 505.05067989,
       502.11177797, 427.192557  , 513.59028711, 477.97357546,
       600.28449278, 507.84505616, 553.39942382, 370.62625275,
       554.78192775, 595.88470519, 528.28304376, 313.57623432,
       448.52076109, 581.71100181, 519.71776178, 324.84915181,
       601.65543792, 463.91415395, 465.58364922, 523.64977073,
       416.83225498, 487.40499643, 410.69835254, 513.73041585,
       391.47429201, 395.35014301, 542.18520447, 497.29085986,
       426.74114709, 395.54014496, 598.49144082, 703.84569417,
       684.83930747, 473.29617572, 282.09672295, 503.77361797,
       766.79605921, 500.67180649, 394.0048709 , 507.83128909,
       461.19291946, 523.12802554, 421.33499034, 423.00487723,
       544.99658762, 558.50121962, 478.23792396, 494.09052431,
       330.72140295, 397.497488  , 448.91524846, 498.43784883,
       494.28795402, 339.39069811, 389.11918034, 512.0248291 ,
       479.03642274, 313.79097721, 463.7839134 , 573.45809705,
       542.97798226, 478.85328823, 490.79376371, 547.57293701,
       532.3128548 , 371.68138027, 484.64860125, 593.86901684,
       587.96281268, 413.77236171, 551.17697716, 425.52108902,
       573.46891113, 589.17138615, 500.43296786, 598.63436286,
       574.68890548, 421.57046691, 408.51584846, 365.98679147,
       594.56887712, 457.48435216, 543.5489021 , 562.55092832,
       515.5536135 , 575.87658795, 517.24027232, 496.76081452,
       487.91526785, 396.8126807 , 356.67809914, 278.9371501 ,
       478.1952756 , 513.97648133, 621.21370168, 623.53027749,
       461.31124404, 407.66375065, 591.69490911, 609.86928288,
       556.02387734, 437.55336239, 523.68978502, 449.95272252,
       443.61500085, 421.77924077, 424.58407751, 619.73783605,
       504.75084841, 424.61678419, 523.24612721, 480.54469215,
       534.99815642, 566.9780584 , 437.94141467, 487.45181736,
       504.85878547, 336.84814316, 506.55009967, 532.28719314,
       463.09822717, 507.76244108, 434.03784243, 506.81811488,
       683.22623707, 640.07440264, 505.57363041, 480.7385924 ,
       431.99855224, 499.41409869, 475.5641466 , 531.63741351,
       481.2958919 , 512.48985574, 411.10936977, 471.47588303,
       518.55517866, 574.99919442, 531.08176622, 534.78550677,
       543.35981878, 607.2311925 , 571.0052771 , 554.1524286 ,
       547.91451139, 500.3126363 , 459.91155119, 449.95042717,
       586.28567202, 504.02387057, 528.27173482, 492.07756368,
       550.5282799 , 646.38504633, 518.36769876, 447.80982588,
       455.87376987, 511.66092506, 404.43243744, 396.3774306 ,
       525.59938291, 528.66673571, 305.28591156, 537.77576392,
       507.11105696, 444.22932312, 628.52421321, 508.28496856,
       532.49596373, 615.74995458, 531.01064502, 516.82833882,
       488.77450238, 616.57535751, 564.79109309, 563.6100984 ,
       445.37326256, 443.01921624, 449.06521185, 481.24439452,
       551.32139633, 457.37963285, 642.66422684, 590.29594387,
       555.25837321, 484.10816342, 554.78470173, 504.20520742,
       416.5392891 , 672.02571285, 384.20341837, 494.9935452 ,
       516.70266592, 518.17946079, 500.06314754, 457.14825137,
       497.32111196, 490.83770446, 608.05281468, 493.43679703,
       412.96190807, 449.22868162, 553.52382187, 501.73940526,
       589.05297187, 558.30186815, 552.97007595, 473.13676823,
       372.92726534, 474.99831478, 389.2011633 , 521.79818539,
       576.95256325, 551.63138862, 609.02819009, 428.84688662,
       547.90402727, 529.70709729, 315.57307136, 481.33157416,
       543.23935158, 430.61433499, 442.28141357, 472.55179111,
       409.27772385, 602.35125617, 498.48396024, 581.23629444,
       619.41448433, 545.0251175 , 347.67896446, 511.76322847,
       480.91543454, 600.05427995, 431.87812893, 543.68236495,
       445.58686108, 563.50422566, 394.44694791, 534.11642618,
       487.48810941, 662.66445458, 451.74717344, 448.78606501,
       464.61815614, 583.81558702, 524.46906224, 635.01301282,
       486.74326557, 424.12042778, 444.51225594, 543.54436153,
       577.32098986, 355.5193908 , 451.42442719, 573.43909159,
       568.8424529 , 496.08586161, 430.32747314, 509.46010327,
       500.56722335, 537.86638053, 473.70082007, 457.4575455 ,
       571.82811375, 515.85184564, 599.40302469, 604.43067518,
       508.96298867, 457.0889004 , 578.19851815, 561.64557457,
       429.35542167, 505.08891671, 545.97247001, 527.57180198,
       577.07898467, 549.63211642, 469.19536187, 458.34338543,
       497.30003376, 439.32692909, 531.48966581, 494.42127389,
       610.59798944, 468.79742768, 500.04423451, 398.48514242,
       445.21418704, 570.22924345, 417.10665974, 435.14550558,
       460.63941331, 532.70947778, 395.29016361, 559.435814  ])

In [28]:
import statsmodels.api as sm
ols=sm.OLS(endog=Y_test,exog=X_test)
result=ols.fit()
print(result.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     Yearly Amount Spent   R-squared:                       0.998
Model:                             OLS   Adj. R-squared:                  0.998
Method:                  Least Squares   F-statistic:                 1.388e+04
Date:                 Mon, 08 Apr 2019   Prob (F-statistic):          1.17e-131
Time:                         23:19:26   Log-Likelihood:                -443.93
No. Observations:                  100   AIC:                             895.9
Df Residuals:                       96   BIC:                             906.3
Df Model:                            4
Covariance Type:             nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Avg. Session Length      9.7857      1.553      6.301      0.000       6.703      12.869
Time on App             34.0589      2.082     16.361      0.000      29.927      38.191
Time on Website        -12.3690      1.303     -9.492      0.000     -14.956      -9.782
Length of Membership    62.9182      2.018     31.172      0.000      58.912      66.925
==============================================================================
Omnibus:                        1.759   Durbin-Watson:                   2.215
Prob(Omnibus):                  0.415   Jarque-Bera (JB):                1.586
Skew:                          -0.307   Prob(JB):                        0.453
Kurtosis:                       2.947   Cond. No.                         53.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [29]:
y_pred_test=l_reg.predict(X_test)

In [30]:
l_reg.score(X_test,Y_test)

0.9891820053530143